config/routes.rb
Rails.application.routes.draw do
  resources :glucose_measurements, path: 'glucose'
  resources :medication_events, path: 'meds'
  resources :carbohydrate_intakes, path: 'carbs'
  resources :physical_exercises, path: 'exercise'
  resources :glycated_haemoglobins, path: 'hba1c'
  resources :blood_pressures, path: 'bp'
  resources :api
  resources :charts

  resources :longterm, path: 'long-term'

  root 'welcome#index'
end

app/models/blood_pressure.rb
class BloodPressure < ActiveRecord::Base
  include PresenterExtension

  def self.short_name
    'Blood Pressure'
  end

  validates :datetime, presence: true
  validates :reading, presence: true
  validates_format_of :reading, with: /[0-9]+\/[0-9]+/
  validates_uniqueness_of :datetime
  default_scope { order('datetime DESC') }
end

app/models/carbohydrate_intake.rb
class CarbohydrateIntake < ActiveRecord::Base
  include PresenterExtension

  def self.short_name
    'Carbs'
  end

  validates :datetime, presence: true
  validates :weight, presence: true, numericality: { greater_than: 0 }
  validates_uniqueness_of :datetime
  default_scope { order('datetime DESC') }
end

app/models/food_combination.rb
class FoodCombination < ActiveRecord::Base
  belongs_to :meal
  belongs_to :food_item 
end

app/models/food_item.rb
class FoodItem < ActiveRecord::Base
  has_many :food_combinations
  has_many :meals, through: :food_combinations

  def self.short_name
    'Food item'
  end

  validates :source, presence: true
  validates :name, presence: true
  validates_uniqueness_of :source, scope: [:name]
end

app/models/glucose_measurement.rb
class GlucoseMeasurement < ActiveRecord::Base
  include PresenterExtension

  def self.short_name
    'Glucose'
  end

  validates :datetime, presence: true
  validates :value, presence: true, numericality: { greater_than: 0 }
  validates_uniqueness_of :datetime
  default_scope { order('datetime DESC') }
end

app/models/glycated_haemoglobin.rb
class GlycatedHaemoglobin < ActiveRecord::Base
  include PresenterExtension

  def self.short_name
    'HbA1c'
  end

  validates :datetime, presence: true
  validates :percentage, presence: true, numericality: { greater_than: 0 }
  validates_uniqueness_of :datetime
  default_scope { order('datetime DESC') }
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  has_many :food_combinations
  has_many :food_items, through: :food_combinations
end

app/models/medication_event.rb
class MedicationEvent < ActiveRecord::Base
  include PresenterExtension

  def self.short_name
    'Meds'
  end

  def self.insulin_types
    [
      'humalog',
      'lantus'
    ]
  end

  validates :datetime, presence: true
  validates :dose, presence: true, numericality: { greater_than: 0 }
  validates :insulin, presence: true, inclusion: { in: insulin_types }
  validates_uniqueness_of :datetime
  default_scope { order('datetime DESC') }
end

app/models/physical_exercise.rb
class PhysicalExercise < ActiveRecord::Base
  include PresenterExtension

  def self.short_name
    'Exercise'
  end

  validates :datetime, presence: true
  validates :duration, presence: true, numericality: { greater_than: 0 }
  validates_uniqueness_of :datetime
  default_scope { order('datetime DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_filter :verify_authenticity_token
  http_basic_authenticate_with name: "#{ENV['API_USER']}", password: "#{ENV['API_PASSWORD']}"

  def create
    data = params['data']
    data = JSON.parse(data) if data.is_a? String
    k = {}
    k['datetime'] = data['datetime']

    case data['type']
      when 'Glucose'
        k['value'] = data['value']
        metric = GlucoseMeasurement.new k

      when 'Medication'
        k['dose'] = data['value']
        k['insulin'] = data['subtype'].downcase
        metric = MedicationEvent.new k

      when 'Food'
        k['weight'] = data['value']
        metric = CarbohydrateIntake.new k

      when 'Exercise'
        k['duration'] = data['value']
        k['description'] = data['subtype'].downcase
        metric = PhysicalExercise.new k

      when 'HbA1c'
        k['percentage'] = data['value']
        metric = GlycatedHaemoglobin.new k

      when 'Blood Pressure'
        k['reading'] = data['value']
        metric = BloodPressure.new k
    end

    if metric.save
      render json: metric, status: :ok and return
    else
      render json: k, status: 400 and return
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def dst_offset
    return 3600 if Time.now.dst?
    return 0
  end
end

app/controllers/charts_controller.rb
class ChartsController < WelcomeController

end

app/controllers/generic_controller.rb
class GenericController < ApplicationController
  include ControllerHelpers

  before_action :require_login

  def index
    @hours = 72
    if params[:hours]
      @hours = hours(params[:hours]) ? hours(params[:hours]) : @hours
    end

    @model = find_class
    @metrics = @model.where(datetime: (Time.now + dst_offset - @hours.hours)..Time.now + dst_offset)

    if @metrics.count < 3
      @metrics = @model.first(3)
    end

    @bucketed_metrics = bucket @metrics

    @with_year = with_year @metrics

    @no_picker = no_picker @metrics

    @has_charts = false
  end

  def show
    @metric = find_class.all.find(params[:id])
  end

  def new
    @metric = find_class.new
  end

  def edit
    @metric = find_class.find(params[:id])
  end

  def create redirect_path = root_path
    @metric = find_class.new(acceptable_params)
    if @metric.save
      redirect_to redirect_path
    else
      render :new
    end
  end

  def update redirect_path = root_path
    @metric = find_class.find(params[:id])

    if @metric.update(acceptable_params)
      redirect_to redirect_path
    else
      render :edit
    end
  end

  def destroy
    @metric = find_class.find(params[:id])
    @metric.destroy

    redirect_to root_path
  end

  private

  def find_class
    params[:controller].classify.constantize
  end

  def metrics_path
    send("#{@metric.class.name.underscore}s_path".to_sym)
  end

  def hours parameter
    # hours since 1970-01-01 i.e. FOREVER
    return ((Time.now.strftime "%s").to_i / 3600) if parameter == '0'
    return parameter.to_i if parameter.to_i > 0
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :require_login

  def index
    @hours = 72
    if params[:hours]
      @hours = hours(params[:hours]) ? hours(params[:hours]) : @hours
    end

    @metrics = []
    [
      GlucoseMeasurement,
      CarbohydrateIntake,
      MedicationEvent
    ].each do |model|
      @metrics.concat model.where(datetime: (Time.now + dst_offset - @hours.hours)..Time.now + dst_offset)
    end

    @metrics = @metrics.sort.reverse

    @bucketed_metrics = {}
    @metrics.group_by do |g|
      g.datetime.strftime "%Y-%m-%d"
    end.each_pair do |date, metric|
      begin
        @bucketed_metrics[date] << metric.first
      rescue NoMethodError
        @bucketed_metrics[date] = metric
      end
    end

    @mixed_metrics = true
    @has_charts = true
  end

  private

  def hours parameter
    # hours since 1970-01-01 i.e. FOREVER
    return ((Time.now.strftime "%s").to_i / 3600) if parameter == '0'
    return parameter.to_i if parameter.to_i > 0
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def models
    [
      GlucoseMeasurement,
      MedicationEvent,
      CarbohydrateIntake,
      PhysicalExercise
    ]
  end

  def longterms
    [
      GlycatedHaemoglobin,
      BloodPressure
    ]
  end

  def class_name instance
    begin
      return instance.name.constantize
    rescue Exception => e
      return instance.class.name.constantize if e.message.match /undefined method `name' for/
    end
  end

  def new_path model
    "new_#{class_name(model).name.underscore}_path".to_sym
  end

  def model_path model
    "#{class_name(model).name.underscore}_path".to_sym
  end

  def model_url model
    "#{class_name(model).name.underscore}_url".to_sym
  end

  def edit_path model
    "edit_#{class_name(model).name.underscore}_path".to_sym
  end
end

app/helpers/blood_pressures_helper.rb
module BloodPressuresHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/longterm_helper.rb
module LongtermHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_footer.html.erb
<div class='footer'>
  <div class='text-center bottom links'>
    <a href='https://github.com/pikesley/correctiondose/issues/new'><i class='fa fa-github'></i> Report issue</a>
  </div>
</div>

app/views/application/_nav.html.erb
<nav class='navbar navbar-default' role='navigation'>
  <div class='container-fluid'>
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#navbar-collapse'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <a class='navbar-brand' href='/'>Home</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class='collapse navbar-collapse' id='navbar-collapse'>
      <ul class='nav navbar-nav' role='tablist' id='main-menu'>
        <li>
          <%= link_to 'Long-term metrics', longterm_index_path %>
        </li>

        <li role='presentation' class='dropdown'>
           <a class='dropdown-toggle' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>
             All Metrics <i class='fa fa-angle-double-down'></i>
           </a>
           <ul class='dropdown-menu' id='secondary-menu'>
             <% models.each do |metric| %>
               <li>
                 <%= link_to metric.short_name, send("#{metric.name.underscore}s_path") %>
               </li>
             <% end %>

             <% longterms.each do |metric| %>
               <li>
                 <%= link_to metric.short_name, send("#{metric.name.underscore}s_path") %>
               </li>
             <% end %>
           </ul>
         </li>
      </ul>
      <p class="navbar-text navbar-right">
        <% if signed_in? %>
          Signed in as <%= current_user.email %> |
          <%= link_to 'Sign out', sign_out_path, method: :delete %>
        <% else %>
          <%= link_to 'Sign in', sign_in_path %>
        <% end %>
      </p>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>